[package]
name = "limousine_example"
version = "0.1.0"
edition = "2021"

[dependencies]
limousine_core = { path = "../limousine_core" }
limousine_derive = { path = "../limousine_derive" }
limousine_engine = { path = "../limousine_engine" }
